/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DetectUI;

import com.sun.glass.ui.Cursor;
import java.awt.TextArea;
import java.io.OutputStream;
import java.io.PrintStream;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author julio
 */
public class DetectorUI extends javax.swing.JFrame {

    /**
     * Creates new form DetectorUI
     */
    public DetectorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jBtnRunAnalise = new javax.swing.JButton();
        txtCaminhoApp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtOutput = new javax.swing.JTextArea();
        jCheckCoupledUI = new javax.swing.JCheckBox();
        jCheckSuspiciousBehavior = new javax.swing.JCheckBox();
        jCheckFlexAdapter = new javax.swing.JCheckBox();
        jCheckGodStyleResource = new javax.swing.JCheckBox();
        jCheckDeepNestedLayout = new javax.swing.JCheckBox();
        jCheckDuplicateStyle = new javax.swing.JCheckBox();
        jCheckBrainUIComponent = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnRunAnalise.setText("Analisar");
        jBtnRunAnalise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRunAnaliseActionPerformed(evt);
            }
        });

        jLabel1.setText("App:");

        jTxtOutput.setColumns(20);
        jTxtOutput.setRows(5);
        jScrollPane1.setViewportView(jTxtOutput);

        jCheckCoupledUI.setText("Coupled UI Component");

        jCheckSuspiciousBehavior.setText("Suspicious Behavior");

        jCheckFlexAdapter.setText("Flex Adapter");

        jCheckGodStyleResource.setText("God Style Resource");

        jCheckDeepNestedLayout.setText("Deep Nested Layout");

        jCheckDuplicateStyle.setText("Duplicate Style Attributes");

        jCheckBrainUIComponent.setText("Brain UI Component");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCaminhoApp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnRunAnalise))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckSuspiciousBehavior)
                            .addComponent(jCheckFlexAdapter)
                            .addComponent(jCheckCoupledUI))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckDeepNestedLayout)
                            .addComponent(jCheckDuplicateStyle)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckGodStyleResource)
                                .addGap(43, 43, 43)
                                .addComponent(jCheckBrainUIComponent)))
                        .addGap(0, 368, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCaminhoApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnRunAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckCoupledUI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckSuspiciousBehavior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckFlexAdapter))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckGodStyleResource)
                            .addComponent(jCheckBrainUIComponent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckDeepNestedLayout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckDuplicateStyle)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

      
    
    private void jBtnRunAnaliseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRunAnaliseActionPerformed
        try{
            
            
            PrintStream ps = new PrintStream(
                new OutputStream() {
                    public void write(int c){
                        jTxtOutput.setText(jTxtOutput.getText() + (char) c);
                    }
                }
            );
            
            System.setOut(ps);
            
            
            if(txtCaminhoApp.getText() != ""){
                
                if(jCheckCoupledUI.isSelected()){
                    AndroidDetector.ImportantSmells.CoupledUIComponent(txtCaminhoApp.getText());
                }                
                
                if(jCheckDeepNestedLayout.isSelected()){
                    AndroidDetector.ImportantSmells.DeepNestedLayout(txtCaminhoApp.getText());
                }
                
                if(jCheckDuplicateStyle.isSelected()){
                    AndroidDetector.ImportantSmells.DuplicateStyleAttributes(txtCaminhoApp.getText());
                }
                
                if(jCheckGodStyleResource.isSelected()){
                    AndroidDetector.ImportantSmells.GodStyleResource(txtCaminhoApp.getText());
                }
                
                if(jCheckSuspiciousBehavior.isSelected()){
                    AndroidDetector.ImportantSmells.SuspiciousBehavior(txtCaminhoApp.getText());
                }
                
                if(jCheckFlexAdapter.isSelected()){
                    AndroidDetector.ImportantSmells.FlexAdapter(txtCaminhoApp.getText());
                }
                
                if(jCheckBrainUIComponent.isSelected()){
                    AndroidDetector.ImportantSmells.BrainUIComponent(txtCaminhoApp.getText());
                }
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Informe Aplicativo para a análise!");                
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        finally{
            
        }
    }//GEN-LAST:event_jBtnRunAnaliseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetectorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetectorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetectorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetectorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetectorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jBtnRunAnalise;
    private javax.swing.JCheckBox jCheckBrainUIComponent;
    private javax.swing.JCheckBox jCheckCoupledUI;
    private javax.swing.JCheckBox jCheckDeepNestedLayout;
    private javax.swing.JCheckBox jCheckDuplicateStyle;
    private javax.swing.JCheckBox jCheckFlexAdapter;
    private javax.swing.JCheckBox jCheckGodStyleResource;
    private javax.swing.JCheckBox jCheckSuspiciousBehavior;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtOutput;
    private javax.swing.JTextField txtCaminhoApp;
    // End of variables declaration//GEN-END:variables
}
